const PROFILE_CHARACTER_LIST = [
  { name: '호랑이', key: 'tiger', source: require('@assets/images/profile-character/tiger.png') },
  { name: '사자', key: 'lion', source: require('@assets/images/profile-character/lion.png') },
  { name: '곰', key: 'bear', source: require('@assets/images/profile-character/bear.png') },
  { name: '여우', key: 'fox', source: require('@assets/images/profile-character/fox.png') },
  { name: '늑대', key: 'wolf', source: require('@assets/images/profile-character/wolf.png') },
  { name: '토끼', key: 'rabbit', source: require('@assets/images/profile-character/rabbit.png') },
  { name: '다람쥐', key: 'squirrel', source: require('@assets/images/profile-character/squirrel.png') },
  { name: '고양이', key: 'cat', source: require('@assets/images/profile-character/cat.png') },
  { name: '강아지', key: 'dog', source: require('@assets/images/profile-character/dog.png') },
  { name: '펭귄', key: 'penguin', source: require('@assets/images/profile-character/penguin.png') },

  { name: '코끼리', key: 'elephant', source: require('@assets/images/profile-character/elephant.png') },
  { name: '기린', key: 'giraffe', source: require('@assets/images/profile-character/giraffe.png') },
  { name: '판다', key: 'panda', source: require('@assets/images/profile-character/panda.png') },
  { name: '코알라', key: 'koala', source: require('@assets/images/profile-character/koala.png') },
  { name: '캥거루', key: 'kangaroo', source: require('@assets/images/profile-character/kangaroo.png') },
  { name: '원숭이', key: 'monkey', source: require('@assets/images/profile-character/monkey.png') },
  { name: '얼룩말', key: 'zebra', source: require('@assets/images/profile-character/zebra.png') },
  { name: '하마', key: 'hippo', source: require('@assets/images/profile-character/hippo.png') },
  { name: '코뿔소', key: 'rhino', source: require('@assets/images/profile-character/rhino.png') },
  { name: '뱀', key: 'snake', source: require('@assets/images/profile-character/snake.png') },

  { name: '독수리', key: 'eagle', source: require('@assets/images/profile-character/eagle.png') },
  { name: '부엉이', key: 'owl', source: require('@assets/images/profile-character/owl.png') },
  { name: '까마귀', key: 'crow', source: require('@assets/images/profile-character/crow.png') },
  { name: '앵무새', key: 'parrot', source: require('@assets/images/profile-character/parrot.png') },
  { name: '백조', key: 'swan', source: require('@assets/images/profile-character/swan.png') },
  { name: '오리', key: 'duck', source: require('@assets/images/profile-character/duck.png') },
  { name: '닭', key: 'chicken', source: require('@assets/images/profile-character/chicken.png') },
  { name: '병아리', key: 'chick', source: require('@assets/images/profile-character/chick.png') },
  { name: '돼지', key: 'pig', source: require('@assets/images/profile-character/pig.png') },
  { name: '소', key: 'cow', source: require('@assets/images/profile-character/cow.png') },

  { name: '양', key: 'sheep', source: require('@assets/images/profile-character/sheep.png') },
  { name: '염소', key: 'goat', source: require('@assets/images/profile-character/goat.png') },
  { name: '말', key: 'horse', source: require('@assets/images/profile-character/horse.png') },
  { name: '당나귀', key: 'donkey', source: require('@assets/images/profile-character/donkey.png') },
  { name: '낙타', key: 'camel', source: require('@assets/images/profile-character/camel.png') },
  { name: '문어', key: 'octopus', source: require('@assets/images/profile-character/octopus.png') },
  { name: '오징어', key: 'squid', source: require('@assets/images/profile-character/squid.png') },
  { name: '개구리', key: 'frog', source: require('@assets/images/profile-character/frog.png') },
  { name: '두더지', key: 'mole', source: require('@assets/images/profile-character/mole.png') },
  { name: '너구리', key: 'raccoon', source: require('@assets/images/profile-character/raccoon.png') },

  { name: '수달', key: 'otter', source: require('@assets/images/profile-character/otter.png') },
  { name: '비버', key: 'beaver', source: require('@assets/images/profile-character/beaver.png') },
  { name: '햄스터', key: 'hamster', source: require('@assets/images/profile-character/hamster.png') },
  { name: '고슴도치', key: 'hedgehog', source: require('@assets/images/profile-character/hedgehog.png') },
  { name: '미어캣', key: 'meerkat', source: require('@assets/images/profile-character/meerkat.png') },
  { name: '알파카', key: 'alpaca', source: require('@assets/images/profile-character/alpaca.png') },
  { name: '사슴', key: 'deer', source: require('@assets/images/profile-character/deer.png') },
  { name: '치타', key: 'cheetah', source: require('@assets/images/profile-character/cheetah.png') },
  { name: '스컹크', key: 'skunk', source: require('@assets/images/profile-character/skunk.png') },
  { name: '물범', key: 'seal', source: require('@assets/images/profile-character/seal.png') },
]

export { PROFILE_CHARACTER_LIST }

